### ISSUE TITLE
implementing user management

### ISSUE THREAD

**Issue by mehdy** [tehpug/Ares#1]
These must be implemented

- [ ] registration
- [ ] login and logout
- [ ] password recovery

**Comment by itmard** [comment]
@mehdy jan I think we can use Django for this part. It has a lot of features to handel User managment, admin panel and more.

**Comment by mehdy** [comment]
@itmard sure! I agree that it's a better choice but for the sake of learning purpose of this project I want to use flask where we need to code more so we'd learn more.

**Comment by itmard** [comment]
@mehdy It's good idea to learn, but we do not need to reinvent the wheel. We can learn new things more complicated than user management in a typical web application which is already provided by a standard web framework like Django

**Comment by mehdy** [comment]
@itmard I disagree. flask is a good choice for this project. maybe the next one.
Thanks for your considerations.

**Comment by ahangarha** [comment]
I think this project has lots of things to be learnt. Choosing flask only
for the sake of learning more on user management, to me, sounds illogical

**Comment by itmard** [comment]
@mehdy Dude you changed you mind ?

**Comment by mehdy** [comment]
@itmard yes, we did

**Comment by ahangarha** [comment]
I wish you would inform us about it. I think it needed to be concluded before getting closed.

**Comment by mehdy** [comment]
Dear @ahangarha. This project has a team that all of its members had an opinion on this decision. You asked how to join the project in this issue #4 and I told you how. but you didn't respond.

**Comment by ahangarha** [comment]
My participation is a different issue. I am already sad for it. I got busy with some other things and couldn't start the work with you guys.
Choosing flask rather than django (which I was more familiar with) was another reason. I was amazed to see the project has started using django. 

This is not relevant to this issue. So, lets not to continue it here.
I hope I find a point to get into the project
