### ISSUE TITLE
Boilerplate problems

### ISSUE THREAD

**Issue by geraneum** [tehpug/Ares#10]
Throughout the the boilerplate code there are many syntactical and some semantic problems that seems to be left there intentionally. Is that so, for sake of debugging practice? @mehdy

**Comment by mehdy** [comment]
yes :)) some of them. could you please comment it which file and line is it?

**Comment by geraneum** [comment]
Although we have a good boilerplate, may I suggest we consider using one of these as starting point to reduce initial friction?
- https://github.com/ryanolson/cookiecutter-webapp
- https://github.com/sloria/cookiecutter-flask

**Comment by mehdy** [comment]
thanks for your suggestions. they're great. you're right the devops things, deployments everything beyond development is not a part of the learning process of project. and I assure you it'll be all done by me :))

I really like the pattern I've been using for my projects. but there's no pressure on it even if we want to use Django over flask I'd be completely ok with it.

I think we need to talk about it and achieve a decision together.

BTW, I really appreciate your effort on the project :)
